<?php $isShowTermsMenuContent = $isShowTermsMenu ? "block": "none" ;?>
<div id="termsMenu" class="con-content" style="display:<?php echo $isShowTermsMenuContent; ?>">
    <div class="head">Persyaratan Penggunaan</div>
    <div class="body">
    <span>Izin untuk menggunakan Situs dan Layanan ini berlaku sampai diakhiri. Izin ini akan berakhir sebagaimana diatur dalam Syarat Layanan ini atau jika Anda gagal mematuhi persyaratan atau ketentuan apapun dari Syarat Layanan ini. Dalam hal demikian, Ngulikin dapat melakukan pengakhiran tersebut dengan atau tanpa memberikan pemberitahuan kepada Anda.</span>
<span>Anda setuju untuk tidak:</span>
<ul>
    <li>mengunggah, memposting, mengirimkan atau menyediakan Konten yang melanggar hukum, berbahaya, mengancam, kasar, melecehkan, mengkhawatirkan, meresahkan, berliku-liku, memfitnah, vulgar, cabul, mencemarkan, invasif terhadap privasi pihak lain, penuh kebencian, atau mengandung unsur SARA atau lainnya;</li>
    <li>melanggar undang-undang, termasuk dengan tidak terbatas pada undang-undang dan peraturan sehubungan dengan batasan ekspor dan impor, hak pihak ketiga atau kebijakan Barang yang Dilarang dan Dibatasi kami;</li>
    <li>menggunakan Layanan untuk merugikan anak di bawah umur dengan cara apapun;</li>
    <li>menggunakan Layanan untuk menyamar sebagai orang atau entitas lain, atau kalau tidak memalsukan afiliasi Anda dengan seseorang atau suatu entitas;</li>
    <li>memalsukan kop atau kalau tidak memanipulasi pengidentifikasi guna menyamarkan asal Konten apapun yang dikirimkan melalui Layanan;</li>
    <li>menghapus pemberitahuan mengenai hak kepemilikan dari Situs;</li>
    <li>menyebabkan, mengizinkan atau memberikan wewenang untuk modifikasi, pembuatan karya turunan, atau penerjemahan Layanan tanpa izin yang jelas dari Ngulikin;</li>
    <li>menggunakan Layanan untuk manfaat pihak ketiga atau dengan cara yang tidak diizinkan oleh izin yang diberikan di sini;</li>
    <li>menggunakan Layanan untuk tujuan menipu;</li>
    <li>memanipulasi harga barang apapun atau mengganggu daftar Pengguna lain;</li>
    <li>melakukan tindakan yang dapat merusak sistem umpan balik atau peringkat;</li>
    <li>mencoba mendekompilasi, merekayasa balik, membongkar atau meretas Layanan (atau bagian apapun darinya), atau mengalahkan atau mengatasi teknologi enkripsi atau langkah-langkah keamanan yang diimplementasikan oleh Ngulikin sehubungan dengan Layanan dan/atau data yang dikirim, diolah atau disimpan oleh Ngulikin;</li>
    <li>memungut atau mengumpulkan informasi apapun tentang atau mengenai pemegang Akun lain, termasuk, dengan tidak terbatas pada, data atau informasi pribadi apapun;</li>
    <li>mengunggah, mengirim email, memposting, mengirimkan atau menyediakan Konten apapun yang tidak berhak untuk Anda sediakan berdasarkan hukum atau ikatan kontrak atau fidusia (seperti informasi orang dalam, informasi eksklusif dan rahasia yang dipelajari atau diungkapkan sebagai bagian dari hubungan kerja atau di bawah perjanjian non pengungkapan);</li>
    <li>mengunggah, mengirim email, memposting, mengirimkan atau menyediakan Konten apapun yang melanggar hak paten, merek dagang, rahasia dagang, hak cipta atau hak kepemilikan lainnya dari pihak mana pun;</li>
    <li>mengunggah, mengirim email, memposting, mengirimkan atau menyediakan iklan, materi promosi yang tidak diinginkan atau tidak sah, "surat sampah", "spam", "surat berantai", "skema piramida", atau bentuk ajakan lainnya yang tidak sah;</li>
    <li>mengunggah, mengirim email, memposting, mengirimkan atau menyediakan materi yang berisikan virus, worm, Trojan-horse perangkat lunak atau kode, rutin, file maupun program komputer lainnya yang dirancang untuk secara langsung atau tidak langsung memengaruhi, memanipulasi, mengganggu, menghancurkan atau membatasi fungsionalitas atau integritas perangkat lunak atau perangkat keras komputer atau data atau perlengkapan telekomunikasi apapun</li>
    <li>mengganggu aliran normal dialog, menyebabkan layar "bergulir" lebih cepat daripada kecepatan mengetik Pengguna Layanan lainnya, atau melakukan tindakan yang secara negatif memengaruhi kemampuan Pengguna lain untuk berkomunikasi dalam waktu nyata;</li>
    <li>memengaruhi, memanipulasi atau mengganggu Layanan atau server atau jaringan yang terhubung ke Layanan atau penggunaan dan kenyamanan menikmati Layanan oleh Pengguna lainnya, atau tidak menaati persyaratan, prosedur, kebijakan atau peraturan jaringan yang terhubung ke Situs;</li>
    <li>melakukan tindakan atau terlibat dalam perilaku yang secara langsung atau tidak langsung dapat merusak, melumpuhkan, membebani secara berlebihan, atau mengganggu Layanan atau server atau jaringan yang terhubung ke Layanan;</li>
    <li>menggunakan Layanan untuk sengaja atau tidak sengaja melanggar hukum, aturan, kode, arahan, pedoman, kebijakan atau peraturan setempat, negara bagian, nasional atau internasional yang berlaku termasuk, dengan tidak terbatas pada, undang-undang dan persyaratan (baik yang berkekuatan hukum maupun tidak) yang berkaitan dengan anti pencucian uang atau anti terorisme;</li>
    <li>menggunakan Layanan dengan melanggar atau untuk menghindari sanksi atau embargo yang diberikan atau diberlakukan oleh Kantor Pengawasan Aset Luar Negeri Departemen Keuangan AS, Dewan Keamanan PBB, Uni Eropa atau Her Majesty’s Treasury;</li>
    <li>menggunakan Layanan untuk melanggar privasi pihak lainnya atau untuk "menguntit" atau mengganggu pihak lain;</li>
    <li>melanggar hak Ngulikin, termasuk setiap hak kekayaan intelektual dan setiap pemboncengan reputasi (passing off) atas hak kekayaan intelektual tersebut;</li>
    <li>
menggunakan Layanan untuk mengumpulkan atau menyimpan data pribadi tentang Pengguna lainnya sehubungan dengan perilaku dan kegiatan terlarang yang ditetapkan di atas; dan/atau
mendaftarkan barang yang melanggar hak cipta, merek dagang atau hak kekayaan intelektual pihak ketiga lainnya atau menggunakan layanan dengan cara yang akan melanggar hak kekayaan intelektual pihak lain;</li>
</ul>
<span>Anda memahami bahwa semua Konten, baik yang diposting untuk umum atau dikirimkan secara pribadi, merupakan tanggung jawab tunggal orang dari mana Konten tersebut berasal. Ini berarti Anda, dan bukan Ngulikin, bertanggung jawab penuh untuk semua Konten yang Anda unggah, posting, kirim melalui email, kirimkan atau sediakan melalui Situs. Anda memahami bahwa dengan menggunakan Situs ini, Anda mungkin akan menemukan Konten yang Anda anggap menyinggung, tidak sopan atau tidak pantas. Sejauh yang diperbolehkan oleh hukum yang berlaku, dalam situasi apapun Ngulikin tidak akan bertanggung jawab dengan cara apapun untuk setiap Konten, termasuk, tetapi tidak terbatas pada, setiap kesalahan atau pembiaran dalam Konten, atau kehilangan maupun kerusakan dalam bentuk apapun yang terjadi sebagai akibat penggunaan, kepercayaan pada Konten yang diposting, diemail, dikirimkan atau disediakan di Situs.</span>
<span>Anda mengakui bahwa Ngulikin dan pihak yang ditunjuk olehnya memiliki hak (tetapi bukan kewajiban) atas kebijakan mereka sendiri untuk melakukan penyaringan awal, menolak, menghapus atau memindahkan Konten, termasuk dengan tidak terbatas pada setiap Konten atau informasi yang diposting oleh Anda, yang tersedia di Situs. Tanpa membatasi ketentuan di atas, Ngulikin dan pihak yang ditunjuk olehnya berhak untuk menghapus Konten (i) yang melanggar Syarat Layanan ini; (ii) jika kami menerima keluhan dari Pengguna lain; (iii) jika kami menerima pemberitahuan tentang pelanggaran kekayaan intelektual atau instruksi hukum lainnya untuk penghapusan; atau (iv) jika Konten tersebut tidak pantas. Kami juga dapat memblokir pengiriman komunikasi (termasuk, dengan tidak terbatas pada, pembaruan status, postingan, pesan dan/atau obrolan) ke atau dari Layanan sebagai bagian dari upaya kami melindungi Layanan atau Pengguna kami, atau menegakkan ketentuan-ketentuan dalam Syarat dan Ketentuan ini. Anda setuju bahwa Anda harus mengevaluasi, dan menanggung semua risiko yang berkaitan dengan penggunaan Konten, termasuk, dengan tidak terbatas pada, kepercayaan pada keakuratan, kelengkapan, atau kegunaan Konten tersebut. Dalam hal ini, Anda mengakui bahwa Anda belum dan, sejauh yang diizinkan oleh hukum yang berlaku, tidak boleh bersandar pada Konten yang dibuat oleh Ngulikin atau dikirimkan ke Ngulikin, termasuk, dengan tidak terbatas pada, informasi di Forum Ngulikin dan di semua bagian lainnya dari Situs.</span>
<span>Anda mengakui, mengizinkan dan setuju bahwa Ngulikin dapat mengakses, menyimpan dan mengungkapkan informasi Akun dan Konten Anda jika diharuskan untuk melakukannya oleh hukum atau berdasarkan perintah pengadilan atau otoritas pemerintah atau pengatur yang memiliki yurisdiksi atas Ngulikin atau dengan itikad baik bahwa akses, penyimpanan atau pengungkapan tersebut memang wajar diperlukan untuk: (a) mematuhi proses hukum; (e) menegakkan Syarat Layanan ini; (c) menanggapi klaim bahwa Konten melanggar hak pihak ketiga; (d) menanggapi permintaan Anda untuk layanan pelanggan; atau (e) melindungi hak, milik atau keselamatan pribadi Ngulikin, Penggunanya dan/atau masyarakat.</span>
<span id="title">PELANGGARAN TERHADAP SYARAT LAYANAN KAMI</span>
<span>Pelanggaran terhadap kebijakan ini dapat mengakibatkan berbagai tindakan, termasuk, dengan tidak terbatas pada, salah satu atau semua dari hal-hal berikut ini:</span>
<ul>
    <li>Penghapusan daftar</li>
    <li>Batasan diberlakukan pada hak Akun</li>
    <li>Penangguhan dan pengakhiran akun</li>
    <li>Tuntutan pidana</li>
    <li>Tindakan perdata, termasuk dengan tidak terbatas pada klaim untuk kerugian dan/atau ganti rugi sementara atau perintah ganti rugi oleh pengadilan.</li>
</ul>
<span>Apabila Anda yakin bahwa seorang Pengguna di Situs kami melanggar Syarat Layanan ini, silakan hubungi <font>info@ngulikin.com</font>.</span>
    </div>
</div>